// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.34.1
// source: quotapb/quota.proto

package quotapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DescribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeRequest) Reset() {
	*x = DescribeRequest{}
	mi := &file_quotapb_quota_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeRequest) ProtoMessage() {}

func (x *DescribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotapb_quota_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeRequest.ProtoReflect.Descriptor instead.
func (*DescribeRequest) Descriptor() ([]byte, []int) {
	return file_quotapb_quota_proto_rawDescGZIP(), []int{0}
}

type ProviderInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Short machine name, e.g. "claude".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL the host's embedded browser should open to start an interactive
	// login for a new account of this provider.
	LoginUrl string `protobuf:"bytes,2,opt,name=login_url,json=loginUrl,proto3" json:"login_url,omitempty"`
	// Domain whose cookies the host captures from the isolated onboarding
	// session once login completes, forming the FetchQuotaRequest credential.
	CookieDomain  string `protobuf:"bytes,3,opt,name=cookie_domain,json=cookieDomain,proto3" json:"cookie_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_quotapb_quota_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_quotapb_quota_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_quotapb_quota_proto_rawDescGZIP(), []int{1}
}

func (x *ProviderInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderInfo) GetLoginUrl() string {
	if x != nil {
		return x.LoginUrl
	}
	return ""
}

func (x *ProviderInfo) GetCookieDomain() string {
	if x != nil {
		return x.CookieDomain
	}
	return ""
}

type FetchQuotaRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Host-assigned label for the account this call is for, echoed back in
	// the snapshot so the host can match responses to accounts when polling
	// several in parallel.
	AccountLabel string `protobuf:"bytes,1,opt,name=account_label,json=accountLabel,proto3" json:"account_label,omitempty"`
	// Cookie name -> value for cookie_domain (or other credential fields for
	// a future non-cookie provider). Never logged by a conforming provider.
	Credential    map[string]string `protobuf:"bytes,2,rep,name=credential,proto3" json:"credential,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchQuotaRequest) Reset() {
	*x = FetchQuotaRequest{}
	mi := &file_quotapb_quota_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchQuotaRequest) ProtoMessage() {}

func (x *FetchQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_quotapb_quota_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchQuotaRequest.ProtoReflect.Descriptor instead.
func (*FetchQuotaRequest) Descriptor() ([]byte, []int) {
	return file_quotapb_quota_proto_rawDescGZIP(), []int{2}
}

func (x *FetchQuotaRequest) GetAccountLabel() string {
	if x != nil {
		return x.AccountLabel
	}
	return ""
}

func (x *FetchQuotaRequest) GetCredential() map[string]string {
	if x != nil {
		return x.Credential
	}
	return nil
}

type QuotaWindow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "session" (e.g. rolling 5h) | "weekly" | provider-defined.
	Label string  `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Used  float64 `protobuf:"fixed64,2,opt,name=used,proto3" json:"used,omitempty"`
	Limit float64 `protobuf:"fixed64,3,opt,name=limit,proto3" json:"limit,omitempty"`
	// e.g. "messages", "tokens", "%".
	Unit string `protobuf:"bytes,4,opt,name=unit,proto3" json:"unit,omitempty"`
	// Unix seconds the window resets at; 0 = unknown.
	ResetsAtUnix  int64 `protobuf:"varint,5,opt,name=resets_at_unix,json=resetsAtUnix,proto3" json:"resets_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaWindow) Reset() {
	*x = QuotaWindow{}
	mi := &file_quotapb_quota_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaWindow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaWindow) ProtoMessage() {}

func (x *QuotaWindow) ProtoReflect() protoreflect.Message {
	mi := &file_quotapb_quota_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaWindow.ProtoReflect.Descriptor instead.
func (*QuotaWindow) Descriptor() ([]byte, []int) {
	return file_quotapb_quota_proto_rawDescGZIP(), []int{3}
}

func (x *QuotaWindow) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *QuotaWindow) GetUsed() float64 {
	if x != nil {
		return x.Used
	}
	return 0
}

func (x *QuotaWindow) GetLimit() float64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *QuotaWindow) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *QuotaWindow) GetResetsAtUnix() int64 {
	if x != nil {
		return x.ResetsAtUnix
	}
	return 0
}

type QuotaSnapshot struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AccountLabel string                 `protobuf:"bytes,1,opt,name=account_label,json=accountLabel,proto3" json:"account_label,omitempty"`
	// Provider-defined plan identifier, e.g. "max", "team_premium".
	PlanKind      string         `protobuf:"bytes,2,opt,name=plan_kind,json=planKind,proto3" json:"plan_kind,omitempty"`
	FetchedAtUnix int64          `protobuf:"varint,3,opt,name=fetched_at_unix,json=fetchedAtUnix,proto3" json:"fetched_at_unix,omitempty"`
	Windows       []*QuotaWindow `protobuf:"bytes,4,rep,name=windows,proto3" json:"windows,omitempty"`
	// Non-fatal issues the host may want to surface (e.g. "endpoint shape
	// drifted, showing last-known values").
	Warnings      []string `protobuf:"bytes,5,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaSnapshot) Reset() {
	*x = QuotaSnapshot{}
	mi := &file_quotapb_quota_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaSnapshot) ProtoMessage() {}

func (x *QuotaSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_quotapb_quota_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaSnapshot.ProtoReflect.Descriptor instead.
func (*QuotaSnapshot) Descriptor() ([]byte, []int) {
	return file_quotapb_quota_proto_rawDescGZIP(), []int{4}
}

func (x *QuotaSnapshot) GetAccountLabel() string {
	if x != nil {
		return x.AccountLabel
	}
	return ""
}

func (x *QuotaSnapshot) GetPlanKind() string {
	if x != nil {
		return x.PlanKind
	}
	return ""
}

func (x *QuotaSnapshot) GetFetchedAtUnix() int64 {
	if x != nil {
		return x.FetchedAtUnix
	}
	return 0
}

func (x *QuotaSnapshot) GetWindows() []*QuotaWindow {
	if x != nil {
		return x.Windows
	}
	return nil
}

func (x *QuotaSnapshot) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

var File_quotapb_quota_proto protoreflect.FileDescriptor

const file_quotapb_quota_proto_rawDesc = "" +
	"\n" +
	"\x13quotapb/quota.proto\x12\n" +
	"aiquota.v1\"\x11\n" +
	"\x0fDescribeRequest\"d\n" +
	"\fProviderInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tlogin_url\x18\x02 \x01(\tR\bloginUrl\x12#\n" +
	"\rcookie_domain\x18\x03 \x01(\tR\fcookieDomain\"\xc6\x01\n" +
	"\x11FetchQuotaRequest\x12#\n" +
	"\raccount_label\x18\x01 \x01(\tR\faccountLabel\x12M\n" +
	"\n" +
	"credential\x18\x02 \x03(\v2-.aiquota.v1.FetchQuotaRequest.CredentialEntryR\n" +
	"credential\x1a=\n" +
	"\x0fCredentialEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x87\x01\n" +
	"\vQuotaWindow\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x12\n" +
	"\x04used\x18\x02 \x01(\x01R\x04used\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x01R\x05limit\x12\x12\n" +
	"\x04unit\x18\x04 \x01(\tR\x04unit\x12$\n" +
	"\x0eresets_at_unix\x18\x05 \x01(\x03R\fresetsAtUnix\"\xc8\x01\n" +
	"\rQuotaSnapshot\x12#\n" +
	"\raccount_label\x18\x01 \x01(\tR\faccountLabel\x12\x1b\n" +
	"\tplan_kind\x18\x02 \x01(\tR\bplanKind\x12&\n" +
	"\x0ffetched_at_unix\x18\x03 \x01(\x03R\rfetchedAtUnix\x121\n" +
	"\awindows\x18\x04 \x03(\v2\x17.aiquota.v1.QuotaWindowR\awindows\x12\x1a\n" +
	"\bwarnings\x18\x05 \x03(\tR\bwarnings2\x9a\x01\n" +
	"\rQuotaProvider\x12A\n" +
	"\bDescribe\x12\x1b.aiquota.v1.DescribeRequest\x1a\x18.aiquota.v1.ProviderInfo\x12F\n" +
	"\n" +
	"FetchQuota\x12\x1d.aiquota.v1.FetchQuotaRequest\x1a\x19.aiquota.v1.QuotaSnapshotB%Z#github.com/go-aiquota/proto/quotapbb\x06proto3"

var (
	file_quotapb_quota_proto_rawDescOnce sync.Once
	file_quotapb_quota_proto_rawDescData []byte
)

func file_quotapb_quota_proto_rawDescGZIP() []byte {
	file_quotapb_quota_proto_rawDescOnce.Do(func() {
		file_quotapb_quota_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quotapb_quota_proto_rawDesc), len(file_quotapb_quota_proto_rawDesc)))
	})
	return file_quotapb_quota_proto_rawDescData
}

var file_quotapb_quota_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_quotapb_quota_proto_goTypes = []any{
	(*DescribeRequest)(nil),   // 0: aiquota.v1.DescribeRequest
	(*ProviderInfo)(nil),      // 1: aiquota.v1.ProviderInfo
	(*FetchQuotaRequest)(nil), // 2: aiquota.v1.FetchQuotaRequest
	(*QuotaWindow)(nil),       // 3: aiquota.v1.QuotaWindow
	(*QuotaSnapshot)(nil),     // 4: aiquota.v1.QuotaSnapshot
	nil,                       // 5: aiquota.v1.FetchQuotaRequest.CredentialEntry
}
var file_quotapb_quota_proto_depIdxs = []int32{
	5, // 0: aiquota.v1.FetchQuotaRequest.credential:type_name -> aiquota.v1.FetchQuotaRequest.CredentialEntry
	3, // 1: aiquota.v1.QuotaSnapshot.windows:type_name -> aiquota.v1.QuotaWindow
	0, // 2: aiquota.v1.QuotaProvider.Describe:input_type -> aiquota.v1.DescribeRequest
	2, // 3: aiquota.v1.QuotaProvider.FetchQuota:input_type -> aiquota.v1.FetchQuotaRequest
	1, // 4: aiquota.v1.QuotaProvider.Describe:output_type -> aiquota.v1.ProviderInfo
	4, // 5: aiquota.v1.QuotaProvider.FetchQuota:output_type -> aiquota.v1.QuotaSnapshot
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_quotapb_quota_proto_init() }
func file_quotapb_quota_proto_init() {
	if File_quotapb_quota_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quotapb_quota_proto_rawDesc), len(file_quotapb_quota_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_quotapb_quota_proto_goTypes,
		DependencyIndexes: file_quotapb_quota_proto_depIdxs,
		MessageInfos:      file_quotapb_quota_proto_msgTypes,
	}.Build()
	File_quotapb_quota_proto = out.File
	file_quotapb_quota_proto_goTypes = nil
	file_quotapb_quota_proto_depIdxs = nil
}
