// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: quotapb/quota.proto

package quotapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuotaProvider_Describe_FullMethodName   = "/aiquota.v1.QuotaProvider/Describe"
	QuotaProvider_FetchQuota_FullMethodName = "/aiquota.v1.QuotaProvider/FetchQuota"
)

// QuotaProviderClient is the client API for QuotaProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QuotaProvider is implemented by every go-aiquota provider plugin
// (hashicorp/go-plugin, gRPC backend) and called by the go-aiquota/tray host.
type QuotaProviderClient interface {
	// Describe returns static facts about the provider: what it's called and,
	// for cookie-based providers, where the host's embedded onboarding browser
	// should navigate and which domain's cookies to capture once login
	// completes. It takes no credential and is safe to call before any
	// account has been onboarded.
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*ProviderInfo, error)
	// FetchQuota returns the current quota snapshot for one account. The
	// credential travels only over this call's request, on go-plugin's
	// AutoMTLS loopback channel; a plugin must not persist it beyond the call.
	FetchQuota(ctx context.Context, in *FetchQuotaRequest, opts ...grpc.CallOption) (*QuotaSnapshot, error)
}

type quotaProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewQuotaProviderClient(cc grpc.ClientConnInterface) QuotaProviderClient {
	return &quotaProviderClient{cc}
}

func (c *quotaProviderClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*ProviderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProviderInfo)
	err := c.cc.Invoke(ctx, QuotaProvider_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quotaProviderClient) FetchQuota(ctx context.Context, in *FetchQuotaRequest, opts ...grpc.CallOption) (*QuotaSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuotaSnapshot)
	err := c.cc.Invoke(ctx, QuotaProvider_FetchQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuotaProviderServer is the server API for QuotaProvider service.
// All implementations must embed UnimplementedQuotaProviderServer
// for forward compatibility.
//
// QuotaProvider is implemented by every go-aiquota provider plugin
// (hashicorp/go-plugin, gRPC backend) and called by the go-aiquota/tray host.
type QuotaProviderServer interface {
	// Describe returns static facts about the provider: what it's called and,
	// for cookie-based providers, where the host's embedded onboarding browser
	// should navigate and which domain's cookies to capture once login
	// completes. It takes no credential and is safe to call before any
	// account has been onboarded.
	Describe(context.Context, *DescribeRequest) (*ProviderInfo, error)
	// FetchQuota returns the current quota snapshot for one account. The
	// credential travels only over this call's request, on go-plugin's
	// AutoMTLS loopback channel; a plugin must not persist it beyond the call.
	FetchQuota(context.Context, *FetchQuotaRequest) (*QuotaSnapshot, error)
	mustEmbedUnimplementedQuotaProviderServer()
}

// UnimplementedQuotaProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuotaProviderServer struct{}

func (UnimplementedQuotaProviderServer) Describe(context.Context, *DescribeRequest) (*ProviderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedQuotaProviderServer) FetchQuota(context.Context, *FetchQuotaRequest) (*QuotaSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchQuota not implemented")
}
func (UnimplementedQuotaProviderServer) mustEmbedUnimplementedQuotaProviderServer() {}
func (UnimplementedQuotaProviderServer) testEmbeddedByValue()                       {}

// UnsafeQuotaProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuotaProviderServer will
// result in compilation errors.
type UnsafeQuotaProviderServer interface {
	mustEmbedUnimplementedQuotaProviderServer()
}

func RegisterQuotaProviderServer(s grpc.ServiceRegistrar, srv QuotaProviderServer) {
	// If the following call panics, it indicates UnimplementedQuotaProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuotaProvider_ServiceDesc, srv)
}

func _QuotaProvider_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaProviderServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaProvider_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaProviderServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuotaProvider_FetchQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuotaProviderServer).FetchQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuotaProvider_FetchQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuotaProviderServer).FetchQuota(ctx, req.(*FetchQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuotaProvider_ServiceDesc is the grpc.ServiceDesc for QuotaProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuotaProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aiquota.v1.QuotaProvider",
	HandlerType: (*QuotaProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _QuotaProvider_Describe_Handler,
		},
		{
			MethodName: "FetchQuota",
			Handler:    _QuotaProvider_FetchQuota_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quotapb/quota.proto",
}
